#!/usr/bin/env bash
# setup nginx web server on an ubuntu machine
apt-get update && apt-get upgrade -y;
apt-get install nginx -y;
ufw allow 'Nginx HTTP';
echo Hello World! > /var/www/html/index.nginx-debian.html;
service nginx restart;
