#!/usr/bin/env bash
#install and set HAProxy on server

apt-get update
apt-get upgrade -y
apt-get install haproxy -y

echo "ENABLED=1" >> /etc/default/haproxy
echo e"
frontend static_assets
  bind :80
  use_backend static_assets

backend static_assets
  balance roundrobin
  server web-01 18.207.112.142:80
  server web-02 100.25.110.244:80" >> /etc/haproxy/haproxy.cfg

service haproxy start
