#!/usr/bin/env bash
#install and set HAProxy on server


sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend abdos_front
	bind *:80
  	mode http
  	default_backend abdos_back
backend abdos_back
  	balance roundrobin
  	server 440397-web-01 18.207.112.142:80 check
  	server 440397-web-02 100.25.110.244:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy start
