#!/usr/bin/env bash
#print the different prompt at 4 and 8 lines
counter=1
while [ $counter -le 10 ]; do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
